### ISSUE TITLE
Display members imported through verification with their type and weight

### ISSUE THREAD

**Issue by sauloperez** [coopdevs/decidim-coopcat#22]
With https://github.com/coopdevs/decidim-coopcat/issues/1 as is, there is no way to know whether the verification entries we just imported are correct. Since the results are anonymous we would need to rely on the CSV we imported from and that's assuming a lot.

**Comment by sseerrggii** [comment]
We want to show all members imported with direct verification in order to check that all information imported is correct.

We can add another button in admin/direct_verifications/direct_verifications similar to /admin/direct_verifications/stats

We should show: 

| User ID        | email           | Metadata  |
| ----- |--------|-------------|
| 73|sergi@example.com |{"nom"=>"sergi alonso", "tipus"=>"treballador", "telefon"=>"653382173", "ponderacio "=>"3"}|

**Comment by sauloperez** [comment]
Being worked on https://github.com/Platoniq/decidim-verifications-direct_verifications/pull/4.

**Comment by sauloperez** [comment]
Closed by https://github.com/Platoniq/decidim-verifications-direct_verifications/pull/7
